name: ismir2019
channels:
  - defaults
  - conda-forge
dependencies:
  - ffmpeg
  - jupyter
  - pip:
    - librosa
    - chainer==3.0.0
    - opencv-python
    - pretty_midi
    - matplotlib
    - oct2py
